[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.116.0"

[context.production.environment]
  HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

